Fix CRAN error
https://cran-archive.r-project.org/web/checks/2021/2021-07-31_check_results_codemetar.html

```
     ══ Failed tests ════════════════════════════════════════════════════════════════
     ── Error (test-codemeta_description.R:62:3): Helper functions work correctly ───
     Error: Timeout was reached: [sysreqs.r-hub.io] Operation timed out after 10000 milliseconds with 0 out of 0 bytes received
     Backtrace:
     █
     1. └─codemetar:::add_software_terms(codemeta, descr) test-codemeta_description.R:62:2
     2. └─codemetar:::parse_sys_reqs(...)
     3. └─codemetar:::get_sys_links(pkg, description = sys_reqs, verbose)
     4. ├─codemetar:::get_url_rhub(...)
     5. │ └─base::sprintf("https://sysreqs.r-hub.io/%s/%s", a, b)
     6. ├─base::unique(...)
     7. └─codemetar:::get_rhub_json_names("pkg", pkg)
     8. ├─base::sapply(...)
     9. │ └─base::lapply(X = X, FUN = FUN, ...)
     10. └─jsonlite::fromJSON(get_url_rhub(a, b), simplifyVector = FALSE)
     11. └─jsonlite:::parse_and_simplify(...)
     12. └─jsonlite:::parseJSON(txt, bigint_as_char)
     13. └─jsonlite:::parse_con(txt, bigint_as_char)
     14. ├─base::open(con, "rb")
     15. └─base::open.connection(con, "rb")
    
     [ FAIL 1 | WARN 0 | SKIP 29 | PASS 80 ]
     Deleting unused snapshots:
     * _snaps/write_codemeta/codemeta.json
     Error: Test failures
     Execution halted
Flavor: r-patched-solaris-x86

```